export const auditCases = [
  { name: 'audit-gm-observer-foundry-hidden-npc', area: 'gm-observer-hidden-npcs',
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: 'audit-gm-observer-foundry-hidden-npc' }] },
  { name: 'audit-scent-gm-selection-gm-vision', area: 'scent-client-isolation',
    observerType: 'character', darkness: true, senses: ['scent'],
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: 'audit-scent-gm-selection-gm-vision' }] },
  ...[false, true].map(observerView => ({ name: `audit-scent-gm-selection-${observerView ? 'observer' : 'normal'}`,
    area: 'scent-client-isolation', observerType: 'character', darkness: true, senses: ['scent'],
    camera: { x: 900, y: 550, scale: 0.7 },
    steps: [{ workflow: `audit-scent-gm-selection-${observerView ? 'observer' : 'normal'}` }] })),
  { name: 'audit-gm-keybindings', area: 'gm-view-keybindings',
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: 'audit-gm-keybindings' }] },
  ...['decision', 'move-cancel'].map(mode => ({ name: `audit-door-approval-${mode}`, area: 'door-approval',
    disposableWorld: true, settings: ['requireGmApprovalForDoorPeek', 'peekSlitAngle', 'peekRange'],
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: `audit-door-approval-${mode}` }] })),
  { name: 'audit-template-cover-saves', area: 'template-reflex-cover',
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: 'audit-template-cover-saves' }] },
  { name: 'audit-sense-the-unseen', area: 'seek-reactions', observerType: 'character',
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: 'audit-sense-the-unseen' }] },
  { name: 'audit-multi-observer-selection', area: 'multi-observer-selection', secondObserver: true,
    disposableWorld: true, settings: ['enableCameraVisionAggregation'],
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: 'audit-multi-observer-selection' }] },
  { name: 'audit-perception-profile-api', area: 'perception-profile-api', secondObserver: true,
    disposableWorld: true, settings: ['autoVisibilityEnabled'],
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: 'audit-perception-profile-api' }] },
  ...['seek', 'search'].map(action => ({ name: `audit-hidden-walls-${action}`, area: 'hidden-wall-discovery',
    secondObserver: true, disposableWorld: true, settings: ['hiddenWallsEnabled', 'seekUseTemplate'],
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: `audit-hidden-walls-${action}` }] })),
  { name: 'audit-combat-start-cover', area: 'combat-start-cover', disposableWorld: true,
    settings: ['computeCoverAtCombatStart'], camera: { x: 900, y: 550, scale: 0.7 },
    steps: [{ workflow: 'audit-combat-start-cover' }] },
  { name: 'audit-party-restoration', area: 'party-restoration', observerType: 'character',
    disposableWorld: true, settings: ['autoVisibilityEnabled'],
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: 'audit-party-restoration' }] },
  ...['hazard', 'loot'].map(type => ({ name: `audit-scene-prep-${type}`, area: 'scene-preparation',
    observerType: 'character', targetType: type, camera: { x: 900, y: 550, scale: 0.7 },
    steps: [{ workflow: 'audit-scene-prep' }] })),
  { name: 'audit-wall-manager', area: 'wall-manager',
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: 'audit-wall-manager' }] },
  ...['two-way', 'replace', 'reverse'].map(mode => ({
    name: `audit-shared-${mode}`, area: 'shared-vision-modes', secondObserver: true,
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: `audit-shared-${mode}` }],
  })),
  ...['Allies', 'Dead', 'Undetected', 'SmallerTokens', 'SameSizeTokens', 'LargerTokens'].map(kind => ({
    name: `audit-cover-ignore-${kind.toLowerCase()}`, area: 'cover-options', secondObserver: true, disposableWorld: true,
    settings: ['autoCoverIgnoreAllies', 'autoCoverIgnoreDead', 'autoCoverIgnoreUndetected',
      'autoCoverIgnoreSmallerTokens', 'autoCoverIgnoreSameSizeTokens', 'autoCoverIgnoreLargerTokens'],
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: `audit-cover-ignore-${kind}` }],
  })),
  { name: 'audit-blinded-movement', area: 'movement-cost',
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: 'audit-blinded-movement' }] },
  { name: 'audit-encounter-master', area: 'encounter-master', secondObserver: true,
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: 'audit-encounter-master' }] },
  ...['hidden', 'concealed', 'undetected'].map(state => ({
    name: `audit-native-condition-${state}`, area: 'system-conditions', disposableWorld: true, secondObserver: true,
    settings: ['systemConditionOverrides'], camera: { x: 900, y: 550, scale: 0.7 },
    steps: [{ workflow: `audit-native-condition-${state}` }],
  })),
  ...['world', 'scene', 'token-vision', 'combat'].map(mode => ({
    name: `audit-avs-${mode}`, area: 'avs-gates', disposableWorld: true,
    settings: ['autoVisibilityEnabled', 'avsOnlyInCombat'],
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: `audit-avs-${mode}` }],
  })),
  ...['individual', 'accept-all', 'reject-all', 'group'].map(mode => ({
    name: `audit-validation-${mode}`, area: 'override-validation', secondObserver: true,
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: `audit-validation-${mode}` }],
  })),
  ...['corner', 'door'].map(mode => ({ name: `audit-peek-${mode}`, area: 'peeking',
    settings: ['requireGmApprovalForDoorPeek', 'peekSlitAngle', 'peekRange'],
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: `audit-peek-${mode}` }],
  })),
  ...['none', 'corner', 'door', 'both'].map(mode => ({
    name: `audit-peek-block-${mode}`, area: 'player-peek-blocking', disposableWorld: true,
    settings: ['playerPeekBlockMode', 'requireGmApprovalForDoorPeek', 'peekSlitAngle', 'peekRange'],
    camera: { x: 900, y: 550, scale: 0.7 },
    steps: [{ workflow: `audit-peek-block-${mode}` }],
  })),
  ...['cancel-reload', 'turn-start', 'turn-end', 'realtime-pause', 'combat-end', 'dialog'].map(mode => ({
    name: `audit-timer-${mode}`, area: 'timed-overrides', disposableWorld: true,
    settings: ['avsOverrideValidationOnTurnChange'],
    camera: { x: 900, y: 550, scale: 0.7 }, steps: [{ workflow: `audit-timer-${mode}` }],
  })),
];
